os: "WMF 5"
version: 1.0.{build}

environment:
  ModuleName: "Communary.PASM"
  psGalleryKey:
    secure: bsxEMSo9+lWrKb0usvlB8RtvGgFcVfV1XxLDjBmP5NwrFv5CHWXAxs2YGQrkJffc
  githubKey:
    secure: IXy+8vrDKX/XYOHF7izRRMC0/r+LFofjs1FPY4ZVyRzTzpwqZdMT8cbjJujzp5Wh

branches:
  only:
    - master

skip_commits:
  message: /updated readme.*/

install:
  - cinst pester -y

build: off

test_script:
  - ps: |
      Write-Host 'Running tests'
      $testResults = '.\TestResults.xml'
      $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResults -PassThru
      Push-AppveyorArtifact $testResults
      if ($res.FailedCount -gt 0) {
          throw "$($res.FailedCount) tests failed."
      }

deploy_script:
  - ps: |
      if ((! $ENV:APPVEYOR_PULL_REQUEST_NUMBER) -and ($ENV:APPVEYOR_REPO_BRANCH -eq 'master')) {
        $ENV:PSModulePath += ";$($ENV:APPVEYOR_BUILD_FOLDER)"
        $null = New-Item -Path $env:ModuleName -Type directory
        #Write-Host "PS Module Path: $($env:psmodulepath)"
        #Import-Module $env:ModuleName -Force
        Write-Host 'Publishing module to PowerShell Gallery'
        Write-Host "AppVeyor Build Folder: $($ENV:APPVEYOR_BUILD_FOLDER)"
        #ls
        [System.Version]$buildNumber = $env:APPVEYOR_BUILD_VERSION
        Update-ModuleManifest -Path ".\$($env:ModuleName).psd1" -ModuleVersion $buildNumber
        Push-AppveyorArtifact ".\$($env:ModuleName).psd1"
        $null = Copy-Item -Path . -Destination $env:ModuleName" -Recurse
        $null = Get-PackageProvider -Name NuGet -ForceBootstrap
        get-module -ListAvailable
        #Publish-Module -Name $env:ModuleName -NuGetApiKey $env:psGalleryKey
        #Publish-Module -Path "$($ENV:APPVEYOR_BUILD_FOLDER)\$($env:ModuleName).psd1" -NuGetApiKey $env:psGalleryKey
      }